#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem "httparty"
  gem "dry-cli"
end

module MetaWeather
  module Api
    class Location
      include HTTParty
      base_uri 'https://www.metaweather.com/api/location'

      def forecast(woeid)
        self.class.get("/#{woeid}")
      end

      def query(query)
        self.class.get('/search/', query: { "query" => query })
      end
    end
  end

  module CLI
    module Commands
      extend Dry::CLI::Registry

      class Version < Dry::CLI::Command
        desc "Print version"

        def call(*)
          puts "1.0.0"
        end
      end

      class Search < Dry::CLI::Command
        desc "Search for weather by location name"

        argument :location, required: true, desc: "Location search string"
        option :for_tomorrow, type: :boolean, default: false, desc: "Print weather just for tomorrow"

        def call(location:, **options)
          api = Api::Location.new
          response = api.query(location)
          if response.any?
            # First result is the most likely hit
            woeid = response.first["woeid"]
            forecast_response = api.forecast(woeid)
            puts "Weather for #{location_name(forecast_response)}"
            weather_data(forecast_response, options).each do |weather_data|
              puts format_weather(weather_data)
            end
          else
            puts "Location not found"
          end
        end

        def location_name(response)
          response['parent']['title']
        end

        def weather_data(response, options = {})
          if options.fetch(:for_tomorrow)
            response["consolidated_weather"]
              .select{|entry| entry["applicable_date"] == (Date.today + 1).to_s}
          else
            response["consolidated_weather"]
          end
        end

        def format_weather(data)
          "#{data['applicable_date']} - #{data['weather_state_name']}"
        end
      end

      register "version", Version, aliases: ["v", "-v", "--version"]
      register "search", Search, aliases: ["search", "s"]
    end
  end
end

Dry::CLI.new(MetaWeather::CLI::Commands).call
