#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem "httparty"
  gem "dry-cli"
end

module MetaWeather
  module Api
    class Location
      include HTTParty
      base_uri 'https://www.metaweather.com/api/location/search'

      def query(location)
        self.class.get('/', query: { "query" => location })
      end

      def lattlong(latt: , long:)
        self.class.get('/', query: { "lattlong" => "#{latt},#{long}" })
      end
    end
  end

  module CLI
    module Commands
      extend Dry::CLI::Registry

      class Version < Dry::CLI::Command
        desc "Print version"

        def call(*)
          puts "1.0.0"
        end
      end

      class Search < Dry::CLI::Command
        desc "Search for weather by location name"

        argument :location, required: true, desc: "Location search string"

        def call(location:)
          response = Api::Location.new.query(location)
          puts response.body
        end
      end

      class LattLong < Dry::CLI::Command
        desc "Search for weather by latitude and longitude, you need to prepend arguments with -- when using negative latt or long"

        argument :latt, required: true
        argument :long, required: true

        example [
          "-- -35.666431 105.972572"
        ]

        def call(latt:, long:)
          response = Api::Location.new.lattlong(latt: latt, long: long)
          puts response.body
        end
      end

      register "version", Version, aliases: ["v", "-v", "--version"]
      register "search", Search, aliases: ["search", "s"]
      register "lattlong", LattLong, aliases: ["lattlong", "ll"]
    end
  end
end

Dry::CLI.new(MetaWeather::CLI::Commands).call
